# Generated by Django 6.0.1 on 2026-01-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("SHIPPED", "Shipped"),
                    ("PAID", "Paid"),
                    ("UNPAID", "Unpaid"),
                ],
                default="UNPAID",
            ),
        ),
    ]
